// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/usecases/session-usecases.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/usecases/session-usecases.go -destination=test/usecases-mocks/login-with-google-usecase-mock.go -package=usecasesmocks
//

// Package usecasesmocks is a generated GoMock package.
package usecasesmocks

import (
	reflect "reflect"

	errors "github.com/henrique998/go-auth/internal/app/errors"
	request "github.com/henrique998/go-auth/internal/app/request"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginWithGoogleUseCase is a mock of LoginWithGoogleUseCase interface.
type MockLoginWithGoogleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLoginWithGoogleUseCaseMockRecorder
}

// MockLoginWithGoogleUseCaseMockRecorder is the mock recorder for MockLoginWithGoogleUseCase.
type MockLoginWithGoogleUseCaseMockRecorder struct {
	mock *MockLoginWithGoogleUseCase
}

// NewMockLoginWithGoogleUseCase creates a new mock instance.
func NewMockLoginWithGoogleUseCase(ctrl *gomock.Controller) *MockLoginWithGoogleUseCase {
	mock := &MockLoginWithGoogleUseCase{ctrl: ctrl}
	mock.recorder = &MockLoginWithGoogleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginWithGoogleUseCase) EXPECT() *MockLoginWithGoogleUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLoginWithGoogleUseCase) Execute(data request.LoginWithGoogleRequest) (string, string, errors.AppErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(errors.AppErr)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockLoginWithGoogleUseCaseMockRecorder) Execute(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLoginWithGoogleUseCase)(nil).Execute), data)
}
