// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/usecases/account-usecases.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/usecases/account-usecases.go -destination=test/usecases-mocks/verify-2fa-code-usecase-mock.go -package=usecasesmocks
//

// Package usecasesmocks is a generated GoMock package.
package usecasesmocks

import (
	reflect "reflect"

	errors "github.com/henrique998/go-auth/internal/app/errors"
	request "github.com/henrique998/go-auth/internal/app/request"
	gomock "go.uber.org/mock/gomock"
)

// MockVerify2faCodeUseCase is a mock of Verify2faCodeUseCase interface.
type MockVerify2faCodeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockVerify2faCodeUseCaseMockRecorder
}

// MockVerify2faCodeUseCaseMockRecorder is the mock recorder for MockVerify2faCodeUseCase.
type MockVerify2faCodeUseCaseMockRecorder struct {
	mock *MockVerify2faCodeUseCase
}

// NewMockVerify2faCodeUseCase creates a new mock instance.
func NewMockVerify2faCodeUseCase(ctrl *gomock.Controller) *MockVerify2faCodeUseCase {
	mock := &MockVerify2faCodeUseCase{ctrl: ctrl}
	mock.recorder = &MockVerify2faCodeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerify2faCodeUseCase) EXPECT() *MockVerify2faCodeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockVerify2faCodeUseCase) Execute(req request.Verify2faCodeRequest) errors.AppErr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", req)
	ret0, _ := ret[0].(errors.AppErr)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockVerify2faCodeUseCaseMockRecorder) Execute(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockVerify2faCodeUseCase)(nil).Execute), req)
}
