// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/usecases/account-usecases.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/usecases/account-usecases.go -destination=test/usecases-mocks/verify-email-usecase-mock.go -package=usecasesmocks
//

// Package usecasesmocks is a generated GoMock package.
package usecasesmocks

import (
	reflect "reflect"

	errors "github.com/henrique998/go-auth/internal/app/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockVerifyEmailUseCase is a mock of VerifyEmailUseCase interface.
type MockVerifyEmailUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyEmailUseCaseMockRecorder
}

// MockVerifyEmailUseCaseMockRecorder is the mock recorder for MockVerifyEmailUseCase.
type MockVerifyEmailUseCaseMockRecorder struct {
	mock *MockVerifyEmailUseCase
}

// NewMockVerifyEmailUseCase creates a new mock instance.
func NewMockVerifyEmailUseCase(ctrl *gomock.Controller) *MockVerifyEmailUseCase {
	mock := &MockVerifyEmailUseCase{ctrl: ctrl}
	mock.recorder = &MockVerifyEmailUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyEmailUseCase) EXPECT() *MockVerifyEmailUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockVerifyEmailUseCase) Execute(token string) errors.AppErr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", token)
	ret0, _ := ret[0].(errors.AppErr)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockVerifyEmailUseCaseMockRecorder) Execute(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockVerifyEmailUseCase)(nil).Execute), token)
}
